---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: build varmint
      run: mkdir varmint_build && cd varmint_build && cmake .. -DBOARD_TO_BUILD=varmint && make
    - name: build pixracer pro
      run: mkdir pixracer_pro_build && cd pixracer_pro_build && cmake .. -DBOARD_TO_BUILD=pixracer_pro && make

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          varmint_build/varmint_10X.hex
          pixracer_pro_build/pixracer_pro.hex

