---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: build varmint
      run: mkdir build && cd build && cmake .. -DBUILD_VARMINT=true && make

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/varmint.hex
