name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: git submodule update --init --recursive
    - name: apt install
      run: sudo apt-get install -y build-essential cmake libgtest-dev
    - name: install gtest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp ./lib/libgtest*.a /usr/lib
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DBOARD_TO_BUILD=test -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: |
        cd build
        make
    - name: test
      run: |
        cd build
        ./test/unit_tests
