name: Varmint Firmware

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: build
      run: mkdir build && cd build && cmake .. -DBUILD_VARMINT=true && make
